import type {Metadata} from "next";

import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

import {getCategories, getResults} from "../services";
import {ListCategories} from "../ui/listcategories";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Challenge-Ml",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {results} = await getResults();

  const categories = await getCategories(results);

  return (
    <html lang="en">
      <body
        className={`${inter.className} container m-auto grid min-h-screen grid-rows-[auto,1fr] px-4`}
      >
        <header className="text-xl font-bold leading-[3rem]">
          <Link className="" href="/">
            Miguelibre
          </Link>
        </header>
        <div className="grid grid-cols-[300px,1fr] gap-5">
          <aside>
            <ListCategories categories={categories} />
          </aside>
          <main className="py-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
